# Task to perform for apache

- name: Install apache2 package
  package: name={{pkg_name}} state=present

- name: update ports.conf file for apache server
  template: src=ports.conf.j2 dest={{ports_dest_path}}

- name: update 000-default.conf file for apache server
  template: src=000-default.conf.j2 dest={{default_dest_path}}

- name: deploy html
  copy: src=index.html dest={{html_dest_path}}
  notify: Restart apache2 service
